@startuml
class subscene.MarketSubScene {
- ArrayList<MarketItem> marketItems
- AnchorPane root
+ {static} Label notEnoughCoin
+ <<Create>> MarketSubScene()
- void createMarketItems()
+ void toggle()
}
class component.bossFight.Status {
- BossFight bossFight
+ <<Create>> Status(BossFight)
+ {static} void drawResultImg(Canvas)
+ {static} void showMsg(Canvas)
+ {static} void drawStatusBox(Canvas)
+ {static} void drawStatusMsg(Canvas)
+ {static} void drawBossConquered(BossFight)
+ {static} void drawGameOver(BossFight)
+ {static} void drawLastResultMsg(Label)
}
abstract class component.unit.BasedUnit {
# Point2D position
# Image image
# ImageView imageView
# Point2D destination
# String imagePath
# double speed
# int coin
+ <<Create>> BasedUnit()
+ <<Create>> BasedUnit(String)
- void initialUnit(String)
+ {abstract}void setPosition(Point2D)
+ void randomDestination()
}
class component.item.equipment.Amulet {
- WritableImage writableImage
+ <<Create>> Amulet()
}
interface component.item.IUsable {
~ void use()
}
class component.item.equipment.Equipment {
# int durability
# EquipmentUtils.TIER tier
+ <<Create>> Equipment(String,Image)
+ void use()
+ int getDurability()
+ void decreaseDurability()
+ void upgrade()
+ EquipmentUtils.TIER getTier()
}
class view.ViewManager {
+ {static} int WINDOW_WIDTH
+ {static} int WINDOW_HEIGHT
- AnchorPane mainPane
- Stage mainStage
- Scene mainScene
- Button startButton
- Button exitButton
- {static} ViewManager instance
- <<Create>> ViewManager()
+ {static} ViewManager getInstance()
- void createMainStage()
+ Stage getMainStage()
- void createButtons()
- void createStartButton()
- void createExitButton()
}
class utils.EquipmentUtils {
- {static} String IMAGE_PATH
- {static} Image IMAGE
+ {static} Image getImage(Equipment)
+ {static} Image getRefineIronImage()
}
enum utils.TIER {
+  Bronze
+  Iron
+  Steel
+  Silver
+  Gold
+  Diamond
+  Mythril
+  Adamantium
+  Orichalcum
+  Excalibur
}
class component.bossFight.MyButtonSkin {
+ <<Create>> MyButtonSkin(Button)
}
class component.item.equipment.Weapon {
- WritableImage writableImage
- int damage
+ <<Create>> Weapon()
+ int getDamage()
+ void upgrade()
}
class component.bossFight.UnitUtils {
+ {static} Outcome generateOutcome(double,double,double)
+ {static} int evaluate(Outcome,Outcome)
+ {static} Image outcomeToImage(Outcome)
}
enum component.bossFight.Outcome {
+  ROCK
+  PAPER
+  SCISSORS
}
enum component.bossFight.Result {
+  WIN
+  LOSS
+  DRAW
}
class component.unit.Slime {
+ <<Create>> Slime()
- void initialSlime()
- void render()
+ ImageView getImageView()
+ void setPosition(Point2D)
+ void walk()
}
class component.inventory.Slot {
- Item item
- ImageView imageView
+ <<Create>> Slot(Item)
- void addEventListeners()
- void addText()
+ Item getItem()
}
class component.bossFight.PigBoss {
+ <<Create>> PigBoss()
+ void shoot()
}
class component.bossFight.RabbitBoss {
+ <<Create>> RabbitBoss()
+ void shoot()
}
class utils.TileRenderer {
}
class application.Main {
+ {static} void main(String[])
+ void start(Stage)
}
class component.bossFight.BossPane {
+ {static} Text bossHpText
+ {static} Boss boss
+ {static} AttackButton atk
+ <<Create>> BossPane(Boss,BossFight)
}
class component.inventory.Inventory {
- {static} Inventory instance
- {static} ArrayList<Slot> slots
- {static} int INVENTORY_SIZE
- {static} AnimationTimer timer
- <<Create>> Inventory()
+ {static} Inventory getInstance()
- void initialInventory()
+ void updateInventory()
+ ArrayList<Slot> getSlots()
+ void reset()
}
abstract class component.bossFight.Boss {
- int hp
- ImageView imageView
- int power
- int level
- UnitUtils.Outcome choice
+ <<Create>> Boss()
+ int getPower()
+ void setPower(int)
+ int getLevel()
+ void setLevel(int)
+ void setChoice(UnitUtils.Outcome)
+ int getHp()
+ void setHp(int)
+ ImageView getImageView()
+ void setImageView(ImageView)
+ UnitUtils.Outcome getChoice()
+ {abstract}void shoot()
}
class component.bossFight.SheepBoss {
+ <<Create>> SheepBoss()
+ void shoot()
}
class component.bossFight.TestBossFight {
+ {static} void main(String[])
+ void start(Stage)
}
class component.item.equipment.Armor {
- WritableImage writableImage
- int defense
+ <<Create>> Armor()
+ int getDefense()
+ void upgrade()
}
class utils.DayNightLight {
- FadeTransition toNightTransition
- FadeTransition toDayTransition
+ <<Create>> DayNightLight()
+ void toNight()
+ void toDay()
}
class subscene.InventorySubScene {
- Label coinLabel
- Label hpLabel
- Label atkLabel
- Label defLabel
- Label armorLabel
- Label weaponLabel
- Label amuletLabel
- {static} int WIDTH
- {static} int HEIGHT
- {static} InventorySubScene instance
+ <<Create>> InventorySubScene()
+ {static} InventorySubScene getInstance()
- void setupStats(AnchorPane)
+ void updateStats()
- void setupItemSlots(AnchorPane)
- void setupEquipment(AnchorPane)
- Label createStyledLabel(String)
}
class component.bossFight.ChickenBoss {
+ <<Create>> ChickenBoss()
+ void shoot()
}
class view.GameViewManager {
- AnchorPane gamePane
- Scene gameScene
- Stage gameStage
- AnimationTimer gameTimer
- Stage mainStage
- MarketSubScene marketSubScene
- InventorySubScene inventorySubScene
- String stoneResourcePath
- String grass1ResourcePath
- String grass2ResourcePath
+ {static} int TILE_SIZE
- Player player
- ArrayList<Slime> slimes
~ DayNightLight dayNightLight
- {static} GameViewManager instance
- Text playerLevel
- <<Create>> GameViewManager()
+ {static} GameViewManager getInstance()
- void initialGameStage()
- void createDayNightLight()
- void loadResources()
- void renderSlime(int)
- void renderTile()
- void createListeners()
- void createGameStage()
- void createSubScenes()
+ void createNewGame(Stage)
- void createTeleport()
- void createGameLoop()
- void updateSlime()
- void updateCamera()
+ {static} boolean isOutsideGame(Point2D)
+ Stage getGameStage()
+ void reset()
}
class component.item.HpPotion {
- int healAmount
- {static} String IMAGE_PATH
- {static} Image IMAGE
- {static} WritableImage writableImage
+ <<Create>> HpPotion(int)
+ void use()
+ void setHealAmount(int)
}
interface component.item.equipment.Refinable {
~ void upgrade()
}
class component.player.Player {
- Point2D position
- Image playerImage
- ImageView playerImageView
- String playerResourcePath
- int horizontalDirection
- int verticalDirection
- WritableImage[] walkUp
- WritableImage[] walkDown
- WritableImage[] walkLeft
- WritableImage[] walkRight
- int direction
- int playerSpeed
- int coin
- {static} Player instance
+ {static} int MAX_HP
+ {static} int level
- {static} int hp
- Armor armor
- Amulet amulet
- Weapon weapon
- int damage
- <<Create>> Player()
+ {static} Player getInstance()
- void loadResource()
- void initialPlayer()
- void render()
+ void update()
+ void playerAnimation(int)
+ ImageView getPlayerImageView()
+ void setHorizontalDirection(int)
+ void setVerticalDirection(int)
+ void setCoin(int)
+ int getCoin()
+ Point2D getPosition()
+ {static} int getHp()
+ void heal(int)
+ void takeDamage(int)
+ void useWeapon()
+ void useAmulet()
+ void setWeapon(Weapon)
+ void setArmor(Armor)
+ void setAmulet(Amulet)
+ Weapon getWeapon()
+ Armor getArmor()
+ Amulet getAmulet()
+ int getAtk()
- int attack(Boss)
+ {static} UnitUtils.Result getResult(Boss,UnitUtils.Outcome)
+ {static} void setHp(int)
+ void reset()
}
class component.bossFight.BossFight {
- BossPane bosspane
- {static} BossFight instance
- {static} Stage mainStage
+ {static} Pane mainPane
+ {static} Canvas statusBox
+ {static} Label resultMsg
+ {static} Label lastResultMsg
+ {static} Canvas resultImg
+ {static} UnitUtils.Outcome myChoice
- <<Create>> BossFight()
+ {static} BossFight getInstance()
- void createMainStage()
+ {static} Stage getMainStage()
}
class component.item.MarketItem {
- Item item
- Text itemName
- Text itemDescription
- Text itemPrice
- Button buyButton
- HBox itemLayout
+ <<Create>> MarketItem(Item,String,int)
- void createUI(Item,String,int)
- void setupEvents(int)
- void buyItem(int)
+ HBox getItemLayout()
+ Text getItemName()
+ Text getItemDescription()
+ Text getItemPrice()
}
abstract class component.item.Item {
# String name
# Image image
# ImageView imageView
- boolean isDestroyed
+ <<Create>> Item(String,Image)
+ ImageView getImageView()
+ Image getImage()
+ void setImage(Image)
+ void setDestroyed(boolean)
+ boolean isDestroyed()
+ String getName()
}
class component.item.RefineIron {
+ <<Create>> RefineIron()
+ void use()
}
class component.bossFight.AttackButton {
- Boss attackedBoss
- BossFight boosfight
+ UnitUtils.Result myResult
- AudioClip explosionSound
+ <<Create>> AttackButton(Boss,BossFight)
+ Button Btn(Image,UnitUtils.Outcome)
}


javafx.scene.SubScene <|-- subscene.MarketSubScene
component.item.equipment.Equipment <|-- component.item.equipment.Amulet
component.item.equipment.Refinable <|.. component.item.equipment.Equipment
component.item.Item <|-- component.item.equipment.Equipment
javafx.scene.control.skin.ButtonSkin <|-- component.bossFight.MyButtonSkin
component.item.equipment.Equipment <|-- component.item.equipment.Weapon
component.unit.BasedUnit <|-- component.unit.Slime
javafx.scene.layout.Pane <|-- component.inventory.Slot
component.bossFight.Boss <|-- component.bossFight.PigBoss
component.bossFight.Boss <|-- component.bossFight.RabbitBoss
javafx.application.Application <|-- application.Main
component.bossFight.VBox <|-- component.bossFight.BossPane
javafx.scene.layout.GridPane <|-- component.inventory.Inventory
component.bossFight.Boss <|-- component.bossFight.SheepBoss
javafx.application.Application <|-- component.bossFight.TestBossFight
component.item.equipment.Equipment <|-- component.item.equipment.Armor
javafx.scene.layout.Pane <|-- utils.DayNightLight
javafx.scene.SubScene <|-- subscene.InventorySubScene
component.bossFight.Boss <|-- component.bossFight.ChickenBoss
component.item.Item <|-- component.item.HpPotion
javafx.scene.layout.StackPane <|-- component.bossFight.BossFight
component.item.IUsable <|.. component.item.Item
component.item.Item <|-- component.item.RefineIron
component.bossFight.HBox <|-- component.bossFight.AttackButton
@enduml